# Generated by Django 6.0.2 on 2026-03-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_feathured',
            new_name='is_featured',
        ),
    ]
